// The blog's data layer is generated by Velite from the Markdown files in
// `src/content/blog/` into the `.velite/` directory at build time. This module
// is the single place that touches the generated output; everything else in
// the app imports typed helpers from here.
import { posts as allGeneratedPosts, type Post } from "../../.velite";

export type { Post };

const byNewestFirst = (a: Post, b: Post): number =>
  new Date(b.date).getTime() - new Date(a.date).getTime();

/**
 * Every post that should be visible publicly — i.e. not flagged as a `draft`.
 * Sorted newest first. Mirrors the `getPublishedProjects` convention so the
 * home page, blog index, sitemap, and RSS feed all share one source of truth.
 *
 * Drafts are intentionally excluded here but remain resolvable by direct URL
 * (see `getPostBySlug`) so they can be previewed before publishing.
 */
export const getPublishedPosts = (): Post[] =>
  allGeneratedPosts.filter((post) => !post.draft).sort(byNewestFirst);

/** Whether there is any published writing to show. */
export const hasPublishedPosts = (): boolean => getPublishedPosts().length > 0;

/** The N most recent published posts. */
export const getRecentPosts = (count: number): Post[] =>
  getPublishedPosts().slice(0, count);

/**
 * The post to lead with on the landing section and blog index: an explicitly
 * pinned post if one exists, otherwise the most recent.
 */
export const getFeaturedPost = (): Post | undefined => {
  const published = getPublishedPosts();
  return published.find((post) => post.featured) ?? published[0];
};

/**
 * Resolve a post by slug across all posts (including drafts) so draft URLs work
 * for preview. Returns `undefined` when nothing matches.
 */
export const getPostBySlug = (slug: string): Post | undefined =>
  allGeneratedPosts.find((post) => post.slug === slug);

export type TagCount = { tag: string; count: number };

/** Unique tags across published posts, ordered by frequency then name. */
export const getAllTags = (): TagCount[] => {
  const counts = new Map<string, number>();
  for (const post of getPublishedPosts()) {
    for (const tag of post.tags) {
      counts.set(tag, (counts.get(tag) ?? 0) + 1);
    }
  }
  return [...counts.entries()]
    .map(([tag, count]) => ({ tag, count }))
    .sort((a, b) => b.count - a.count || a.tag.localeCompare(b.tag));
};

/** Canonical path for a post's detail page. */
export const postPath = (slug: string): string => `/blog/${slug}`;

/** Human-readable post date, e.g. "June 30, 2026". */
export const formatPostDate = (iso: string): string =>
  new Date(iso).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

/** "5 min read" helper from Velite's computed reading time. */
export const formatReadingTime = (minutes: number): string =>
  `${Math.max(1, Math.round(minutes))} min read`;
